language: julia
julia:
  - 0.6
os:
  - linux
notifications:
  email: mkolar@gmail.com
sudo: false
script:
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.build("$name")'
  - if [ -f test/runtests.jl ]; then
  -   julia --check-bounds=yes test/runtests.jl
  - fi
