language: julia
julia:
  - 0.7
os:
  - linux
notifications:
  email: mkolar@gmail.com
addons:
    apt_packages:
        - gfortran
sudo: false
script:
  - julia -e 'Pkg.clone(pwd()); Pkg.build("ProximalBase"); Pkg.test("ProximalBase"; coverage=true)'
after_success:
    - echo $TRAVIS_JULIA_VERSION
    - julia -e 'Pkg.add("Coverage"); cd(Pkg.dir("ProximalBase")); using Coverage; Codecov.submit(process_folder())'
