language: julia
julia:
  - 0.7
os:
  - linux
notifications:
  email: mkolar@gmail.com
addons:
    apt_packages:
        - gfortran
sudo: false
script:
  - julia -e 'import Pkg; Pkg.clone(pwd(), "ProximalBase"); Pkg.build("ProximalBase"); Pkg.test("ProximalBase"; coverage=true)'
after_success:
    - echo $TRAVIS_JULIA_VERSION
    - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
